name: Documentation

on:
  push:
    tags:
      - "*"

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependent software
        run: |
          conda info
          conda env update --file doc-dev.yml --name base 

      - name: Install dependencies
        run: |
          pip3 install jinja2 Pygments

      - name: Install dependencies
        run: sudo apt-get install libboost-dev

      - name: Build
        run: |
          cmake -S. -Bbuild
          cmake --build build --target GenerateDocs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/documentation/doxygen/html
